---
version: '3'
services:
  elasticsearch:
    env_file: elk.env
    # Equivalent to:
    # docker run --rm --cap-add=IPC_LOCK --ulimit memlock=-1:-1 --ulimit nofile=65536:65536 -t -P --memory="2g" -e "discovery.zen.minimum_master_nodes=1" \ 
    #   -v elasticsearch-data:/usr/share/elasticsearch/data jcap/elasticsearch
    build:
      context: elasticsearch
      args:
        ELASTIC_VERSION: "${ELASTIC_VERSION}"
        ES_DOWNLOAD_URL: "${ES_DOWNLOAD_URL}"
    cap_add:
      - IPC_LOCK
    environment:
      - discovery.zen.minimum_master_nodes=1
    image: "jcap/elasticsearch"
    deploy:
      resources:
        limits:
          memory: 2g
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    network_mode: "bridge"
  logstash:
    env_file: elk.env
    build:
      context: logstash
      args:
        ELASTIC_VERSION: "${ELASTIC_VERSION}"
        LOGSTASH_DOWNLOAD_URL: "${LOGSTASH_DOWNLOAD_URL}"
        LOGSTASH_PACK_URL: "${LOGSTASH_PACK_URL}"
    image: "jcap/logstash"
    network_mode: "bridge"
    links:
      - elasticsearch
    depends_on:
      - elasticsearch
    volumes:
      - /var/log:/mnt/hostlog
  kibana:
    env_file: elk.env
    build:
      context: kibana
      args:
        ELASTIC_VERSION: "${ELASTIC_VERSION}"
        KIBANA_DOWNLOAD_URL: "${KIBANA_DOWNLOAD_URL}"
    image: "jcap/kibana"
    network_mode: "bridge"
    links:
      - elasticsearch
    depends_on:
      - elasticsearch
      - logstash
    #ports:
    #  - 5601:5601

    # Configure certificate and key files to enable SSL. The certificate
    # provided in the example is self-signed, and thus insecure. It should
    # only be used for experimentation, never in production.
    #
    #environment:
    #  - SERVER_SSL_CERT=/usr/share/kibana/config/kibana.example.org.crt
    #  - SERVER_SSL_KEY=/usr/share/kibana/config/kibana.example.org.key

volumes:
  elasticsearch-data:
